# Generated by Django 4.1.5 on 2023-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('name2', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(max_length=10, verbose_name='Пол')),
            ],
        ),
    ]
